# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ojUrTWNe8N2-atPs_Mk73g4lUKGUzsvI
"""

# Instalowanie bibliotek, "!" ozacza wykonanie komendy w terminalu a nie w Pythonie:

!apt update && apt install xvfb
!pip install gym-notebook-wrapper
!pip install gym[classic_control]
!pip install gym[box2d]
!pip install opencv-python-headless
!pip install stable-baselines3
!pip install pyglet
!pip install 'shimmy>=0.2.1'

import gym

from stable_baselines3 import A2C
from stable_baselines3.common.env_util import make_vec_env

# Parallel environments
env3 = make_vec_env("CartPole-v1", n_envs=1)

model = A2C("MlpPolicy", env3, verbose=1)
model.learn(total_timesteps=15000)
model.save("a2c_cartpole")

# !pip3 install gym[box2d]
import gnwrapper
import gym

env = gnwrapper.Monitor(gym.make("CartPole-v1"), directory="./p/")

observation = env.reset()
total_reward = 0

while True:
    action, _ = model.predict(observation)
    observation, reward, done, info = env.step(action)
    total_reward += reward
    if done:
        observation = env.reset()  # Reset the environment when done
        break

env.display()  # Close the environment to save the recorded video

# You can display the recorded video separately if you like, using the Monitor's directory
# You can do this outside of the code

print(f"Total reward: {total_reward}")